// udhr-rosetta.test.mjs — the Rosetta's ground, pinned. THE-MORAL-CORE:
// "the charters are GIVEN affordances in the hyperlexicon, with the charters
// named as giver." The rosetta driver (udhr-rosetta.mjs) is what makes that
// omnilingual: it reads the UDHR in the reference languages (eng, fra),
// finds the slots where the under-read languages extracted nothing, and
// projects the missing norms into each target's completed hyperlexicon —
// corroborated projections GIVEN with the UDHR as giver, 1-of-2 projections
// candidates, each witnessed by the target's OWN aligned sentence bytes.
//
// P88 (a guard that is never reached passes forever): this test READS the
// driver's actual output on every suite run, exactly as the proxy/charter
// would consume the ground — the gate cannot be assumed working from a
// fixture nobody loads.

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const RESULTS = path.join(HERE, "../eval/lavar/results/");
const LANGUAGES = ["eng", "fra", "spa", "rus", "arb", "cmn_hans"];

// The driver output is regenerated by `node native/eval/lavar/udhr-rosetta.mjs`;
// a missing artifact is a typed gap, not a silently-missing ground.
const hasGround = (l) => existsSync(`${RESULTS}udhr-${l}.ground.hyperlexicon.json`);

const loadGround = (l) => JSON.parse(readFileSync(`${RESULTS}udhr-${l}.ground.hyperlexicon.json`, "utf8"));

test("the Rosetta emits a ground hyperlexicon for every official language", () => {
  for (const l of LANGUAGES) {
    assert.ok(hasGround(l), `udhr-${l}.ground.hyperlexicon.json missing — run native/eval/lavar/udhr-rosetta.mjs`);
    const g = loadGround(l);
    assert.equal(g.schema, "EOHyperlexicon@1");
    assert.equal(g.language, l);
  }
});

test("every language's ground is GIVEN with the UDHR as giver (the ethos is named)", () => {
  for (const l of LANGUAGES) {
    const g = loadGround(l);
    assert.ok(g.given > 0, `${l}: the ground must carry GIVEN affordances — candidates alone cannot govern`);
    const hl = g.hyperlexicon.composition ?? {};
    const given = Object.values(hl).filter((e) => e.standing === "given");
    for (const e of given.slice(0, 3)) {
      assert.match(String(e.giver), /Universal Declaration of Human Rights/, `${l}: a GIVEN norm must name the UDHR as giver`);
      assert.ok((e.witnesses ?? []).length > 0, `${l}: a GIVEN norm must carry its own language's aligned sentence as witness`);
    }
  }
});

test("the under-read languages carry Rosetta-projected norms their own read never extracted", () => {
  // cmn_hans reads 0 edges (the S103 caseless-script gap) — every norm in its
  // ground is projected. That is the Rosetta's whole job: the target's own
  // reader went dark, and the aligned norm still stands on its own bytes.
  const cmn = loadGround("cmn_hans");
  const hl = cmn.hyperlexicon.composition ?? {};
  const projected = Object.values(hl).filter((e) => e.meta?.projected);
  assert.ok(projected.length >= 100, `cmn_hans: expected 100+ projected norms, got ${projected.length}`);
  for (const e of projected.slice(0, 5)) {
    assert.ok(e.meta.corroborated, "a projected norm should be Rosetta-corroborated (both references read it)");
    assert.ok((e.witnesses ?? []).length > 0, "a projected norm is witnessed by the target's own aligned sentence");
    assert.ok(/[\u4e00-\u9fff]/.test(String(e.witnesses[0] ?? "")), "the witness is the Chinese sentence, not the English one");
  }
});

test("a 1-of-2 projection is a candidate, never a given (the Rosetta falsification)", () => {
  // spa's uncorroborated slots (only one reference read a norm there) must
  // enter as candidates — a lone reference is incomplete adjudication.
  const spa = loadGround("spa");
  const hl = spa.hyperlexicon.composition ?? {};
  const uncorrob = Object.values(hl).filter((e) => e.meta?.projected && e.meta?.corroborated === false);
  for (const e of uncorrob) {
    assert.equal(e.standing, "candidate", `a 1-of-2 projection must not be GIVEN: ${e.left} → ${e.right}`);
  }
});

test("the reference languages' own reads ARE the ground — no projection needed", () => {
  for (const l of ["eng", "fra"]) {
    const g = loadGround(l);
    const hl = g.hyperlexicon.composition ?? {};
    const projected = Object.values(hl).filter((e) => e.meta?.projected);
    assert.equal(projected.length, 0, `${l}: a reference language needs no Rosetta projection`);
    assert.ok(g.given >= 90, `${l}: the reference's own read should carry the full norm set (got ${g.given})`);
  }
});

test("the driver's summary is consistent with the ground files", () => {
  const summaryPath = `${RESULTS}udhr-rosetta.json`;
  assert.ok(existsSync(summaryPath), "udhr-rosetta.json missing — run the driver");
  const summary = JSON.parse(readFileSync(summaryPath, "utf8"));
  assert.equal(summary.schema, "UDHRRosetta@1");
  assert.ok(summary.referenceSlots >= 50, `reference slots should cover the 30-article grid (got ${summary.referenceSlots})`);
  assert.ok(summary.referenceSlotsCorroborated >= 45, `most reference slots should be corroborated by both eng+fra (got ${summary.referenceSlotsCorroborated})`);
  for (const l of LANGUAGES) {
    assert.equal(summary.groundFiles[l], `udhr-${l}.ground.hyperlexicon.json`);
    assert.equal(summary.ground[l].language, l);
  }
});