// ═══ LOVELACE · TEACH IT TO FISH ═══ A NET-NEW APP FROM A PROMPT — no pack: the sources are found, the fields are traced, the app is assembled from them.
//   node native/the-fold/app-generic.mjs --task "build me an app that shows the air quality anywhere" --out <dir>
// The generic half of the app door. Where app-door.js finds a need no pack grounds, this builds for it anyway, the way the pack path never could:
//   1 Unraveling   the request's phrases are cut at their seams into the needs that do not depend on each other (organs/unraveling.js)
//   2 Cultivating  for each data need, find-samples goes and gets a REAL sample of an open JSON source (search, read, rank, fetch under a budget)
//   3 Tracing      every field the app shows is a path found, by name evidence and in every fetched variant of the call; the bytes are the oracle
//   4 the place    a need whose call takes a latitude and a longitude gets a geocoder found the same way, so "anywhere" is a place name -> coordinates
//   5 assemble     a server whose only knowledge is those traced paths, a page that renders them, and an about page that lists every address and byte hash
//   6 drive        the server is started, asked for a place, and its answer is compared with an independent re-fetch of the underlying call read at the same paths
// STEERED, said once: the cores, the declared offsets and names, and the page's layout are my hand. The sources, their addresses, the paths and the values are not.
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { spawn } from "node:child_process";
import { phrasesOf } from "../organs/app-door.js";
import { partsOfRequest } from "../organs/unraveling.js";
import { leavesOf } from "../organs/tracing.js";
import { findSamples } from "./find-samples.mjs";
import { contractFromSample, candidatePaths, nameEvidence } from "./sample-contract.mjs";
import { openSeenLedger } from "./comp-research.mjs";

const norm = (s) => String(s).toLowerCase().replace(/[^a-z0-9]/g, "");
const STOP = new Set(["the", "and", "for", "app", "anywhere", "show", "shows"]);
const lastKey = (p) => p.replace(/\[\d*\]/g, "").split(".").pop();
const sha = (s) => crypto.createHash("sha256").update(s).digest("hex");

const notUnits = (c) => !/unit/i.test(c.kind.split(".")[0]);
/** the person's own WORDS (whole tokens, punctuation stripped) that equal a path kind's last key -> fields; "time" does not match "times" inside another phrase's word, only the word itself */
export function namedFields(words, doc, { strings = false } = {}) {
  const toks = new Set((String(words).toLowerCase().match(/[a-z0-9][a-z0-9._]*/g) ?? []).map(norm)), seen = new Set(), out = [];
  for (const c of candidatePaths(doc, { strings })) { const k = lastKey(c.kind), n = norm(k); if (notUnits(c) && n.length >= 2 && toks.has(n) && !seen.has(n)) { seen.add(n); out.push({ label: k, path: c.path }); } }
  return out;
}
/** with none named: every numeric kind whose key the sample's OWN address asked for (current=pm10,pm2_5 -> pm10, pm2_5) */
export function askedFields(url, doc) {
  const asked = new Set([...new URL(url).searchParams.values()].flatMap((v) => v.split(",")).map(norm)), seen = new Set(), out = [];
  for (const c of candidatePaths(doc)) { const k = lastKey(c.kind), n = norm(k); if (notUnits(c) && asked.has(n) && !seen.has(n)) { seen.add(n); out.push({ label: k, path: c.path }); } }
  return out;
}
/** a part's own words name keys this document already holds -> those fields (a need the source in hand already covers) */
export function coveredBy(part, doc) {
  const out = [], seen = new Set();
  for (const w of part.toLowerCase().match(/[a-z]{4,}/g) ?? []) for (const c of candidatePaths(doc, { strings: true })) { const k = lastKey(c.kind), n = norm(k); if (notUnits(c) && n.includes(norm(w)) && !seen.has(n)) { seen.add(n); out.push({ label: k, path: c.path }); } }
  return out;
}
/** the unit a traced field travels with: a string leaf in a sibling `…units` container under the same last key */
export function unitOf(doc, fieldPath) {
  const key = lastKey(fieldPath), seg = fieldPath.split(".")[0].replace(/\[\d+\]/g, "");
  const u = leavesOf(doc).find((l) => typeof l.value === "string" && lastKey(l.path) === key && l.path.split(".")[0].startsWith(seg) && /unit/i.test(l.path.split(".")[0]));
  return u ? { path: u.path, value: u.value } : null;
}

/** the sample whose values a person reads as "now": the one with the most scalar numeric leaves outside arrays */
function pickSample(kept) {
  const scalar = (k) => leavesOf(JSON.parse(k.bytes)).filter((l) => typeof l.value === "number" && !/\[\d+\]/.test(l.path)).length;
  return [...kept].sort((a, b) => scalar(b) - scalar(a))[0];
}

const SERVER = (cfg) => `// generated by eoreader7 native/the-fold/app-generic.mjs — knows only the traced paths in cfg.json
import http from "node:http"; import fs from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
const here = path.dirname(fileURLToPath(import.meta.url)), cfg = JSON.parse(fs.readFileSync(path.join(here, "cfg.json"), "utf8"));
const at = (doc, p) => (p == null ? undefined : p.split(/[.\\[\\]]+/).filter(Boolean).reduce((o, k) => (o == null ? undefined : o[k]), doc));
const get = async (u) => { const r = await fetch(u, { headers: { "user-agent": "generated-app/1 (eoreader7)" } }); if (!r.ok) throw new Error(u.split("?")[0] + " answered " + r.status); return r.json(); };
const sub = (url, params) => { const u = new URL(url); for (const [k, v] of Object.entries(params)) u.searchParams.set(k, v); return u.toString(); };
async function read(place) {
  const g = cfg.place ? await get(sub(cfg.place.url, { [cfg.place.nameParam]: place })) : null;
  if (cfg.place && at(g, cfg.place.latitude) == null) return { gap: "no place named " + place };
  const fields = [];
  for (const s of cfg.sources) {
    const params = s.latParam ? { [s.latParam]: at(g, cfg.place.latitude), [s.lonParam]: at(g, cfg.place.longitude) } : {};
    const d = await get(sub(s.url, params));
    for (const f of s.fields) fields.push({ label: f.label, value: at(d, f.path), unit: f.unitPath ? at(d, f.unitPath) : null, path: f.path, source: s.id });
  }
  return { place: cfg.place ? { name: at(g, cfg.place.nameField) ?? place, latitude: at(g, cfg.place.latitude), longitude: at(g, cfg.place.longitude) } : { name: place }, fields };
}
http.createServer(async (req, res) => {
  const u = new URL(req.url, "http://x");
  try {
    if (u.pathname === "/") { res.writeHead(200, { "content-type": "text/html; charset=utf-8" }); return res.end(fs.readFileSync(path.join(here, "index.html"))); }
    if (u.pathname === "/about.html") { res.writeHead(200, { "content-type": "text/html; charset=utf-8" }); return res.end(fs.readFileSync(path.join(here, "about.html"))); }
    if (u.pathname === "/api/read") { const out = await read(u.searchParams.get("place") || cfg.defaultPlace); res.writeHead(200, { "content-type": "application/json" }); return res.end(JSON.stringify(out)); }
    res.writeHead(404); res.end("not found");
  } catch (e) { res.writeHead(502, { "content-type": "application/json" }); res.end(JSON.stringify({ gap: String(e.message).slice(0, 200) })); }
}).listen(Number(process.argv[2] || process.env.PORT || 8860), "127.0.0.1", () => console.log("listening"));
`;

const PAGE = (cfg) => `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${cfg.title}</title>
<style>:root{--bg:#f6f7f9;--fg:#15181d;--mut:#5b6472;--line:#dde1e7;--surf:#fff}@media(prefers-color-scheme:dark){:root{--bg:#0f1318;--fg:#e6e9ee;--mut:#9aa4b2;--line:#252c36;--surf:#171c23}}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.45 system-ui,sans-serif;padding:16px}main{max-width:640px;margin:0 auto}h1{font-size:1.2rem;margin:0 0 12px}form{display:flex;gap:8px;margin-bottom:16px}input{flex:1;padding:10px;border:1px solid var(--line);border-radius:8px;background:var(--surf);color:var(--fg);font:inherit}button{padding:10px 14px;border:0;border-radius:8px;background:var(--fg);color:var(--bg);font:inherit}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.card{background:var(--surf);border:1px solid var(--line);border-radius:12px;padding:14px;overflow-wrap:anywhere}.card b{display:block;font-size:1.5rem}.card span{color:var(--mut)}.gap{padding:14px;border:1px dashed var(--line);border-radius:12px;color:var(--mut)}footer{margin-top:20px;color:var(--mut);font-size:.85rem}</style>
<main><h1 id="h">${cfg.title}</h1><form id="f"><input id="p" value="${cfg.defaultPlace}" aria-label="place"><button>Show</button></form><div id="o" class="grid"></div><footer><a href="/about.html">where every value comes from</a></footer></main>
<script>const o=document.getElementById('o'),esc=s=>String(s).replace(/</g,'&lt;');async function go(p){o.innerHTML='<div class="gap">loading…</div>';try{const r=await (await fetch('/api/read?place='+encodeURIComponent(p))).json();if(r.gap){o.innerHTML='<div class="gap">'+esc(r.gap)+'</div>';return}document.getElementById('h').textContent=${JSON.stringify(cfg.title)}+' — '+r.place.name;o.innerHTML=r.fields.map(f=>'<div class="card"><span>'+esc(f.label.replace(/_/g,' '))+'</span><b>'+esc(f.value??'—')+'</b><span>'+esc(f.unit||'')+'</span></div>').join('')}catch(e){o.innerHTML='<div class="gap">could not read: '+esc(e.message)+'</div>'}}document.getElementById('f').onsubmit=e=>{e.preventDefault();go(document.getElementById('p').value)};go(document.getElementById('p').value)</script></html>`;

export function assembleGeneric({ out, cfg, provenance }) {
  fs.rmSync(out, { recursive: true, force: true }); fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, "cfg.json"), JSON.stringify(cfg, null, 1));
  fs.writeFileSync(path.join(out, "server.mjs"), SERVER(cfg));
  fs.writeFileSync(path.join(out, "index.html"), PAGE(cfg));
  const esc = (s) => String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  fs.writeFileSync(path.join(out, "about.html"), `<!doctype html><meta charset="utf-8"><title>Provenance</title><body style="font:15px/1.5 system-ui;max-width:760px;margin:24px auto;padding:0 16px"><h1>Where every value comes from</h1><p>Built from the prompt: <i>${esc(provenance.task)}</i></p>${provenance.sources.map((s) => `<h2>${esc(s.role)}</h2><p><code>${esc(s.url)}</code><br>sample sha256 <code>${esc(s.sha256)}</code>, ${esc(s.leaves)} leaves</p><ul>${s.fields.map((f) => `<li><b>${esc(f.label)}</b> at <code>${esc(f.path)}</code> — ${esc(f.by)}; traced in ${esc(f.docs)} fetched variants</li>`).join("")}</ul>`).join("")}${(provenance.notBuilt ?? []).length ? `<h2>Asked for, not built</h2><ul>${provenance.notBuilt.map((n) => `<li>${esc(n.need)} — ${esc(n.why)}</li>`).join("")}</ul>` : ""}<p>Every search, page, fetch and refusal is on file with the build (seen.jsonl).</p>`);
  return { ok: true, dir: out };
}

async function waitUp(port, ms = 8000) { const t0 = Date.now(); for (;;) { try { const r = await fetch(`http://127.0.0.1:${port}/about.html`); if (r.ok) return true; } catch {} if (Date.now() - t0 > ms) return false; await new Promise((r) => setTimeout(r, 200)); } }

/** drive: start the generated server, ask it for places, compare each answer with an independent re-fetch of every source read at the same paths */
export async function driveGeneric({ dir, cfg, places, port = 8861 }) {
  const proc = spawn(process.execPath, [path.join(dir, "server.mjs"), String(port)], { env: { ...process.env }, stdio: "ignore" });
  const rows = [];
  try {
    if (!(await waitUp(port))) return { ok: false, gap: "the generated server did not start" };
    for (const place of places) {
      const ask = async () => (await fetch(`http://127.0.0.1:${port}/api/read?place=${encodeURIComponent(place)}`)).json();
      let a = await ask(), retried = false;
      if (a.gap && /fetch failed/.test(a.gap)) { retried = true; a = await ask(); } // a network blip between the generated server and a public API is recorded, once
      if (a.gap) { rows.push({ place, retried, ok: false, why: a.gap }); continue; }
      const bad = []; let refetch = null;
      for (const s of cfg.sources) {
        const u = new URL(s.url); if (s.latParam) { u.searchParams.set(s.latParam, a.place.latitude); u.searchParams.set(s.lonParam, a.place.longitude); }
        let d = null;
        for (let attempt = 0; attempt < 2 && !d; attempt++) { try { d = await (await fetch(u, { headers: { "user-agent": "generated-app-check/1" } })).json(); } catch (e) { refetch = `independent re-fetch of ${u.origin} failed: ${String(e?.cause?.code ?? e?.message ?? e).slice(0, 80)}`; await new Promise((r) => setTimeout(r, 1500)); } }
        if (!d) { bad.push(`(${s.id}) not re-fetched`); continue; }
        const by = new Map(leavesOf(d).map((l) => [l.path, l.value]));
        for (const f of a.fields.filter((x) => x.source === s.id)) if (by.get(f.path) !== f.value || f.value == null) bad.push(f.label);
      }
      rows.push({ place, retried, refetch, resolved: a.place.name, ok: !bad.length, fields: a.fields.map((f) => `${f.label}=${f.value}${f.unit ?? ""}`), bad });
    }
  } finally { proc.kill(); }
  return { ok: rows.length > 0 && rows.every((r) => r.ok), rows };
}

const placeNameParam = (url) => [...new URL(url).searchParams].find(([k, v]) => /^(name|q|query|city|place|location|search)$/i.test(k) && !Number.isFinite(Number(v)))?.[0] ?? null;

export async function buildGenericApp({ task, out, model = "qwen2.5-coder:1.5b", log = () => {}, findImpl = findSamples }) {
  fs.mkdirSync(out, { recursive: true });
  const L = openSeenLedger(out), phrases = phrasesOf(task), parts = partsOfRequest(phrases, STOP);
  L.see("task", { task, phrases, unraveled: { status: parts.status, parts: parts.parts, seams: parts.seams } });
  if (!phrases.length) return { ok: false, gap: { type: "no_needs", detail: "no data phrase could be read from the prompt" } };
  const sources = [], notBuilt = [];
  for (const part of parts.parts) {
    const need = part.join(" ");
    // a need the source already in hand covers (its words are keys in that document) is read from it; otherwise a new source is found
    const held = sources.find((s) => coveredBy(need, s.doc).length);
    if (held) { const f = coveredBy(need, held.doc).filter((x) => !held.fields.some((y) => y.path === x.path)); held.fields.push(...f.map((x) => ({ ...x, need }))); L.see("need-covered", { need, by: held.url, fields: f }); continue; }
    log(`need: ${need}`);
    const data = await findImpl({ need: `${need} api latitude longitude`, out: path.join(out, `find-${sources.length}`), needCount: 2, budget: 8, minNumbers: 0 });
    if (!data.kept.length) { notBuilt.push({ need, why: "no open JSON source was found and kept; nothing is shown that was not fetched" }); L.see("need-not-built", { need, why: "no source kept" }); continue; }
    const kept = data.kept.map((k) => ({ ...k, bytes: fs.readFileSync(path.join(out, `find-${sources.length}`, k.file), "utf8") }));
    // prefer a sample whose keys already hold the need's own words, else the one with the most scalar numbers
    const sample = kept.find((k) => coveredBy(need, JSON.parse(k.bytes)).length) ?? pickSample(kept), doc = JSON.parse(sample.bytes);
    const fields = (coveredBy(need, doc).length ? coveredBy(need, doc) : namedFields(need, doc, { strings: true }).length ? namedFields(need, doc, { strings: true }) : askedFields(sample.url, doc)).map((f) => ({ ...f, need }));
    L.see("fields-read", { need, from: coveredBy(need, doc).length ? "the need's own words as keys" : "the prompt or the sample's own request", fields });
    if (!fields.length) { notBuilt.push({ need, why: "no field could be tied to the need, the prompt or the request" }); continue; }
    sources.push({ id: `s${sources.length}`, need, url: sample.url, sha256: sample.sha256, leaves: sample.evidence.leaves, doc, bytes: sample.bytes, fields });
  }
  if (!sources.length) return { ok: false, gap: { type: "no_source", need: notBuilt.map((n) => n.need).join(", "), detail: "no open JSON source was found and kept for any need; nothing is shown that was not fetched" }, ledger: L.file };
  const provenance = { task, sources: [], notBuilt }, cfgSources = [];
  for (const s of sources) {
    const dc = await contractFromSample({ url: s.url, bytes: s.bytes, fields: s.fields.map((f) => f.label), strings: true, model, out: path.join(out, `contract-${s.id}`) });
    const bound = dc.fields.filter((f) => f.status === "bound");
    for (const f of dc.fields.filter((f) => f.status !== "bound")) notBuilt.push({ need: `${s.need}: ${f.field}`, why: f.why ?? "not bound" });
    if (!bound.length) continue;
    const u = new URL(s.url); let latParam = null, lonParam = null; for (const k of u.searchParams.keys()) { if (/^lat/i.test(k)) latParam = k; if (/^(lon|lng)/i.test(k)) lonParam = k; }
    cfgSources.push({ id: s.id, url: s.url, latParam: latParam && lonParam ? latParam : null, lonParam: latParam && lonParam ? lonParam : null, fields: bound.map((f) => ({ label: lastKey(f.pointed), path: f.pointed, unitPath: unitOf(s.doc, f.pointed)?.path ?? null })) });
    provenance.sources.push({ role: `data: ${s.need}`, url: s.url, sha256: s.sha256, leaves: s.leaves, fields: bound.map((f) => ({ label: lastKey(f.pointed), path: f.pointed, by: f.by, docs: dc.docs })) });
  }
  if (!cfgSources.length) return { ok: false, gap: { type: "no_bound_fields", detail: "no field passed name evidence and tracing" }, ledger: L.file };
  const cfg = { title: sources.map((s) => s.need).join(" · ").replace(/\b\w/g, (c) => c.toUpperCase()), defaultPlace: "London", sources: cfgSources, place: null };
  if (cfgSources.some((s) => s.latParam)) {
    const geo = await findImpl({ need: "geocoding place name to latitude and longitude", out: path.join(out, "find-place"), needCount: 1, budget: 8, minNumbers: 1 });
    if (!geo.kept.length) return { ok: false, gap: { type: "no_geocoder", detail: "the data calls take coordinates and no geocoding source was found; a place name cannot be turned into them" }, ledger: L.file };
    const gk = geo.kept[0], gbytes = fs.readFileSync(path.join(out, "find-place", gk.file), "utf8"), gc = await contractFromSample({ url: gk.url, bytes: gbytes, fields: ["latitude", "longitude", "name"], strings: true, model, out: path.join(out, "contract-place") });
    const gb = Object.fromEntries(gc.fields.filter((f) => f.status === "bound").map((f) => [f.field, f.pointed])), nameKey = placeNameParam(gk.url);
    if (!gb.latitude || !gb.longitude || !nameKey) return { ok: false, gap: { type: "geocoder_unbound", detail: "latitude, longitude or the place-name parameter could not be traced in the geocoder's sample", fields: gc.fields }, ledger: L.file };
    cfg.place = { url: gk.url, nameParam: nameKey, latitude: gb.latitude, longitude: gb.longitude, nameField: gb.name ?? null };
    provenance.sources.push({ role: "place", url: gk.url, sha256: gk.sha256, leaves: gk.evidence.leaves, fields: gc.fields.filter((f) => f.status === "bound").map((f) => ({ label: f.field, path: f.pointed, by: f.by, docs: gc.docs })) });
  }
  assembleGeneric({ out: path.join(out, "app"), cfg, provenance });
  L.see("assembled", { dir: path.join(out, "app"), sources: cfg.sources.length, fields: cfg.sources.reduce((n, s) => n + s.fields.length, 0), place: !!cfg.place, notBuilt });
  const drive = await driveGeneric({ dir: path.join(out, "app"), cfg, places: ["Paris", "Nairobi", "Lima"] });
  L.see("driven", drive);
  return { ok: drive.ok, dir: path.join(out, "app"), cfg, drive, notBuilt, ledger: L.file };
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  const arg = (k, d) => { const i = process.argv.indexOf(`--${k}`); return i >= 0 ? process.argv[i + 1] : d; };
  const r = await buildGenericApp({ task: arg("task"), out: path.resolve(arg("out", "./generic-app")), model: arg("model", "qwen2.5-coder:1.5b"), log: (m) => console.log("·", m) });
  console.log(JSON.stringify({ ok: r.ok, gap: r.gap, dir: r.dir, sources: r.cfg?.sources, notBuilt: r.notBuilt, drive: r.drive }, null, 1));
}
